#-----------------------------
#
# configdata, for the workflow
#
#-----------------------------
path_to_data: "/data/scratch/manuez42/ideas/data/1000-Genome-Project/gruppe6"
files_per_bin: 1
size: 0

reference_genome: "/data/scratch/manuez42/ideas/data/NCBI-reference/GRCh38.fna"
database_SNPs: "/data/scratch/manuez42/ideas/data/dbSNP/dbSNP.vcf.gz"
# SNPs: 
# path_to_nodelist: 

threads: 8

# execution
# snakemake --dryrun --use-conda -s Snakefile --slurm "sbatch -t 80  --nodes=2 --mem=100G --partition='big'" -j 1000 --latency-wait 10