#-----------------------------
#
# configdata, for the workflow
#
#-----------------------------

number_of_bins: 2
number_of_nodes: 2

path_to_ref: "/data/scratch/manuez42/data/genom/bacteria_30G/files/"
path_to_reads: "/data/scratch/manuez42/ideas/data/1000-Genome-Project/gruppe6"

# path_to_index: "/data/scratch/manuez42/ideas/data//NCBI-reference/"
# path_to_reference: "/data/scratch/manuez42/ideas/data/NCBI-reference/GRCh38.fna"
# database_SNPs: "/data/scratch/manuez42/ideas/data/dbSNP/dbSNP.vcf.gz"

working_dir: "/data/scratch/manuez42/A2-jobgranularity/mg_6/data/"

# for indexing
# t = threads, m = memory
index_t: 16
index_m: 9000

# for nodes computation
threads: 8
memory: 3000

# for cplex results
# path_to_nodelist: 



# execution:
# snakemake --dryrun --verbose --use-conda -s Snakefile --execution slurm -j 1000 --latency-wait 10
# changes in Snakemake > 8; not backward compatible,
# but solves a few of our problems with cluster ressource allocation
# needs profile for cluster and more parameters
# see readme